# Generated by Django 3.2.12 on 2022-12-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('raca', models.CharField(max_length=30, verbose_name='Raça')),
                ('peso', models.IntegerField(verbose_name='Peso')),
                ('tipo', models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], max_length=30, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logradouro', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('numero', models.CharField(max_length=5, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=30, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.DateField(verbose_name='Dia da Reserva')),
                ('id_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cadastropet')),
                ('id_reponsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='cadastropet',
            name='id_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.responsavel'),
        ),
    ]
